### ISSUE TITLE
Installation instructions: ilastik-forge release is just version 0.1

### ISSUE THREAD

**Issue by psobolewskiPhD** [ilastik/ilastik-napari#10]
The install instructions to use:
`mamba create -y -c ilastik-forge -n my-napari-env napari-ilastik`
result in outdated plugin:
```
  + napari-ilastik                          0.1  py_0                  ilastik-forge/noarch          11kB
```
because the package is out-dated:
https://anaconda.org/ilastik-forge/napari-ilastik/files

`pypi` has latest version.

This seems like it should work:
```
mamba create -y -n napari-il -c ilastik-forge -c conda-forge python=3.9 napari fastfilters
mamba activate napari-il
pip install ilastik-napari
```
but I hit issue with napari[all] in dependencies, see:
https://github.com/ilastik/ilastik-napari/issues/9

Edit: note that adding `-c conda-forge` in the instructions can be important, because some users may not have that channel, see for example the image.sc thread below.

**Comment by btbest** [comment]
The instructions have been updated to instruct installation through pip, as we are not supporting the conda release anymore.

Will need to see about removing the deprecated conda package.
