### ISSUE TITLE
Python 3.9 OS-X support

### ISSUE THREAD

**Issue by alisterburt** [ilastik/ilastik-napari#3]
Hi Emil/Ilastik team, I was hoping to test out `napari-ilastik` locally on a mac and ran into issues with `fastfilters` - it appears the `ilastik-forge/fastfilters` package only supports up to python 3.8. On Big-Sur and above napari requires the conda-forge version of python 3.9, see [here](https://forum.image.sc/t/issue-with-downloading-napari-on-mac-m1-chip/53961/7) for details.

```sh
(napari-ilastik) ➜  fastfilters git:(master) ✗ conda install -c ilastik-forge fastfilters
Collecting package metadata (current_repodata.json): done
Solving environment: - 
Found conflicts! Looking for incompatible packages.                                                                                                                                                failed                                                                                                                                                                                                 

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - fastfilters -> python[version='>=3.7,<3.8.0a0']

Your python: python=3.9
```

I tried to build `fastfilters` locally but ran into issues with both apple clang and conda-forge clang without immediate success but I'm not an expert at compiling these things.

Is updating the `fastfilters` conda-forge recipe to support 3.9 on your radar? Is compatibility with big-sur macs for `napari-ilastik` planned to be supported at some point?

Thanks!

**Comment by emilmelnikov** [comment]
Hi @alisterburt,

Unfortunately, upgrading fastfilters to Python 3.8+ is not as straightforward as it seems, so we cannot promise any dates (this is one of the reasons classic ilastik is still on Python 3.7).

Regarding macOS Big Sur, it seems that napari requires only Python 3.7 and later both [via conda](https://github.com/conda-forge/napari-feedstock/blob/fad2b03debd9d4ead6c932936c9d683c977e1577/recipe/meta.yaml#L28) and [via pip](https://github.com/napari/napari/blob/2381c71b942492cfd8f2d402a803aca54a14337e/setup.cfg#L38). I am personally using napari and fastfilters installed in the same environment on Big Sur.

**Comment by alisterburt** [comment]
Thanks for the details/info and sorry to hear it's not as easy as it could be!

Interesting about Big Sur, it may be that 3.9 is only a requirement on the M1 chip then, I'll have a look around

**Comment by psobolewskiPhD** [comment]
Looks like `fastfilters` on ilastik-forge supports 3.9 now:
https://anaconda.org/ilastik-forge/fastfilters/files
